window.TOOTOO_CONFIG = {
  owner: 'theo-armour',
  repo: 'pages',
  appName: 'Pages',
  storagePrefix: 'ta-pages',
  sourceRepoUrl: 'https://github.com/theo-armour/pages',
  themeColor: '#e67e22',
  subtitle: '',
  faviconLetters: 'PG',
  faviconColor: '#e67e22',
  faviconFile: 'favicon.ico',
  subtitle: 'a GitHub repository browser',
  headingFontUrl: 'https://fonts.googleapis.com/css2?family=Patua+One&display=swap',
  headingFont: '"Patua One", serif',
  hiddenFiles: [ 'tootoo.config.js' ],
  hiddenFolders: [ 'Images' ],
};
